packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - vue-router@5.3.0
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
overrides:
  serialize-javascript@<7.0.5: ">=7.0.5"
  serialize-javascript@<=7.0.2: ">=7.0.3"
