version: "3.9"

services:
  app:
    image: "ghcr.io/gabe565/relax-sounds"
    build:
      args:
        FONTAWESOME_NPM_AUTH_TOKEN: "$FONTAWESOME_NPM_AUTH_TOKEN"
      context: .
    ports:
      - "80:80"
    volumes:
      - "./data:/data:ro"
